### ISSUE TITLE
RNN vs BG/NBD

### ISSUE THREAD

**Issue by sophia-wright-blue** [kaislar/Customer-classification-RFM#1]
thanks for releasing this repo, did you get a chance to compare the output from your RNN to a typical RFM model (like BG/NBD)?

**Comment by kaislar** [comment]
It was part of a school project to experiment with deep learning so i had not the opportunity to use other models nor to compare with the state of the art.

**Comment by sophia-wright-blue** [comment]
thanks for replying @kaislar , and thanks again for releasing this code, i'll try experimenting with it
